#!/usr/bin/env python3
# MUST output a single JSON object to STDOUT, no extra prints.
import json, sys

info = {
    "project_type": "other",           # one of: scrapy, casperjs, other
    "spiders": ["run"]                 # list of non-empty STRING spider names
}
json.dump(info, sys.stdout)
sys.stdout.write("\n")
